### ISSUE TITLE
blinker case study does not work.

### ISSUE THREAD

**Issue by TomyYamy** [arturmrowca/bayspec#1]
I'm trying to evaluate blinker case study in your paper "Learning Temporal Specifications from Imperfect Traces Using Bayesian Inference"
I think we may run it with changing main code
https://github.com/arturmrowca/bayspec/blob/ea527eec27427f8667bfd88c135a3751c0260b45/main.py#L9
to
```
start_evaluation(option=6)
```
This enables to run blinker case study code
`bayspec/evaluation/plots/ev_case_study_blinker.py`

However, I get error below.
```
$ /bin/python3 bayspec/main.py
Traceback (most recent call last):
  File "bayspec/main.py", line 9, in <module>
    start_evaluation(option=6)
  File "bayspec/evaluation/eval_main.py", line 26, in start_evaluation
    case_study_blinker_evaluation()
  File "bayspec/evaluation/eval_main.py", line 53, in case_study_blinker_evaluation
    case_study_blinker.start()
  File "bayspec/evaluation/plots/ev_case_study_blinker.py", line 14, in start
    with open("blinker_model/blinker_tscbn1.tscbn", "rb") as in_stream:
FileNotFoundError: [Errno 2] No such file or directory: 'blinker_model/blinker_tscbn1.tscbn'
```
It seems blinker_model/blinker_tscbn1.tscbn that is input of this code does not exist in the repo.

How I can represent the blinker case study?
Could you please commit blinker_tscbn1.tscbn and other necessary data?

**Comment by MartinNoc** [comment]
Hi @TomyYamy,
thank you for reporting this issue.
I will check the availability of the model and push it to the repo if available.

Cheers

**Comment by arturmrowca** [comment]
Hello,


Thank you for contacting me.

To get the evaluation results you need to follow these 3 steps.

The sequences for training are uploaded.
If you want to get the model you need to run structure discovery first.
Then, this model can be used during Parameter estimation.
Based on this all the Inference approaches are run.

The code for those three steps is uploaded.

Does this suffice you or do you still need the tscbn file?

Best wishes
Artur


TomyYamy ***@***.***> schrieb am Fr., 29. Juli 2022, 00:22:
